### ISSUE TITLE
PyPA is seeking for a paid contractor for dependency resolution

### ISSUE THREAD

**Issue by vpoulailleau** [sdispater/mixology#3]
I just wanted to let you know that PyPA is looking for someone to do similar work.

This is paid (important) work.

In case you haven't heard about this, it's here: http://pyfound.blogspot.com/2019/11/seeking-developers-for-paid-contract.html

BTW, after having use poetry a little bit, I really like it.

Et puisque tu es visiblement français, sache que poetry me sert pour https://github.com/vpoulailleau/padpo qui sert à la traduction en français de la doc officielle de Python.

**Comment by ddelange** [comment]
https://github.com/pypa/pip/issues/988#issuecomment-565757071

**Comment by vpoulailleau** [comment]
> […] Poetry's author has pitched in himself […]

@ddelange Thanks for the answer.
